[[constraint]]
  version = "1.0.0"
  name = "github.com/auth0-community/go-auth0"

[[constraint]]
  name = "github.com/devopsfaith/krakend"
  version = "0.7.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/square/go-jose.v2"
  version = "2.1.6"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
